# Generated by Django 5.0.2 on 2024-02-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenthistory',
            name='position',
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.jobtitle'),
        ),
    ]
