# Generated by Django 5.0.2 on 2024-03-01 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employmenthistory_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1899, 12, 31, 22, 30, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
