# Generated by Django 5.0.2 on 2024-03-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_date_of_birth'),
        ('accounts', '0007_userprofile_email'),
    ]

    operations = [
    ]
